### ISSUE TITLE
ngrx/devtools import with SystemJS not working.

### ISSUE THREAD

**Issue by bertrandg** [ngrx/devtools#10]
Thanks for these great tools!
I use ngrx/store@1.3.3 with systemJS and it works very well.
But I just tried to add ngrx/devtools@1.3.3 exactly the same way and it fails with this error:
`GET http://localhost:3000/node_modules/@ngrx/store/dist/dist/store-backend.js 404 (Not Found)`

Here is my systemJS config:

```javascript
	System.config({
		packages: {
			src: {
				format: 'register',
				defaultExtension: 'js'
			},
			'@ngrx/store': {
				main: 'index.js',
				format: 'cjs'           
			},
			'@ngrx/devtools': {
				main: 'index.js',
				format: 'cjs'           
			} 
		},
		map: {
			'@ngrx/store': 'node_modules/@ngrx/store/dist',
			'@ngrx/devtools': 'node_modules/@ngrx/devtools/dist'
		}
	});
```

That's weid because `store-backend.js` is loaded correctly from `http://localhost:3000/node_modules/@ngrx/store/dist/store-backend.js` when I don't use/import @ngrx/devtools..

Any ideas how to solve it?

**Comment by brandonroberts** [comment]
Here is a working SystemJS config example: https://github.com/ngrx/store/issues/18#issuecomment-195893273

**Comment by bertrandg** [comment]
Nice, it works! :)
Here is my config for others:

```javascript
System.config({
	packages: {
		src: {
			format: 'register',
			defaultExtension: 'js'
		},
		'@ngrx/store': {
			main: 'dist/index.js',
			format: 'cjs'           
		},
		'@ngrx/devtools': {
			main: 'dist/index.js',
			format: 'cjs'
		} 
	},
	map: {
		'@ngrx': 'node_modules/@ngrx'
	}
});
```
