### ISSUE TITLE
Customization does not work

### ISSUE THREAD

**Issue by jusefb** [ngrx/devtools#9]
Hi,

Well done on getting this out to the world, this will be an awesome help in developing Angular 2 apps. I was trying to follow the Readme but could not get the Customization part to work. The devtoolsConfig does not seem to exist in the @ngrx/devtools namespace.

Here is what I have in my package.json:

    "@ngrx/devtools": "^1.3.1",
    "@ngrx/store": "^1.3.3",

Kind regards

Jusef

**Comment by MikeRyan52** [comment]
Hi Jusef,

The customization options had not yet been published when you tried to use them. Sorry about that! Try pulling down the latest version (1.3.3) and you should be able to customize.

**Comment by jusefb** [comment]
I will try that thanks
